{
 "title": "CronusFarm Overview",
 "tags": [ "cronusfarm" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "전체 환경", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "온도(현재)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"temp\")\n  |> last()"
    }
   ]
  },
  {
   "title": "습도(현재)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"humidity\")\n  |> last()"
    }
   ]
  },
  {
   "title": "EC(현재)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"ec\")\n  |> last()"
    }
   ]
  },
  {
   "title": "pH(현재)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"ph\")\n  |> last()"
    }
   ]
  },
  {
   "title": "온도 그래프",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"temp\")"
    }
   ]
  },
  {
   "title": "습도 그래프",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"humidity\")"
    }
   ]
  },
  {
   "title": "EC 그래프",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"ec\")"
    }
   ]
  },
  {
   "title": "pH 그래프",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"ph\")"
    }
   ]
  },
  { "title": "A Bed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "LED A1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"led_a1\")\n  |> last()"
    }
   ]
  },
  {
   "title": "LED A2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"led_a2\")\n  |> last()"
    }
   ]
  },
  { "title": "B Bed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "LED B1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"led_b1\")\n  |> last()"
    }
   ]
  },
  { "title": "C Bed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "PUMP C1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"pump_a1\")\n  |> last()"
    }
   ]
  },
  {
   "title": "PUMP C2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"pump_a2\")\n  |> last()"
    }
   ]
  },
  { "title": "D Bed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "PUMP D1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"pump_b1\")\n  |> last()"
    }
   ]
  },
  {
   "title": "PUMP D2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"pump_b2\")\n  |> last()"
    }
   ]
  },
  { "title": "FAN (임시 I2C)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "FAN A1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"fan_a1\")\n  |> last()"
    }
   ]
  },
  {
   "title": "FAN B1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"fan_b1\")\n  |> last()"
    }
   ]
  },
  {
   "title": "FAN B2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"fan_b2\")\n  |> last()"
    }
   ]
  }
 ]
}