{
 "title": "CronusFarm 장치",
 "tags": [
  "cronusfarm",
  "device"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "💡 LED", "type": "row", "gridPos": { "x": 0, "y": 0, "w": 24, "h": 1 } },
  {
   "title": "LED A1",
   "type": "stat",
   "gridPos": { "x": 0, "y": 1, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"led_a1\")\n  |> last()"
    }
   ]
  },
  {
   "title": "LED A2",
   "type": "stat",
   "gridPos": { "x": 4, "y": 1, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"led_a2\")\n  |> last()"
    }
   ]
  },
  {
   "title": "LED B1",
   "type": "stat",
   "gridPos": { "x": 8, "y": 1, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"led_b1\")\n  |> last()"
    }
   ]
  },
  { "title": "💧 PUMP", "type": "row", "gridPos": { "x": 0, "y": 5, "w": 24, "h": 1 } },
  {
   "title": "PUMP C1",
   "type": "stat",
   "gridPos": { "x": 0, "y": 6, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"pump_a1\")\n  |> last()"
    }
   ]
  },
  {
   "title": "PUMP C2",
   "type": "stat",
   "gridPos": { "x": 4, "y": 6, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"pump_a2\")\n  |> last()"
    }
   ]
  },
  {
   "title": "PUMP D1",
   "type": "stat",
   "gridPos": { "x": 8, "y": 6, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"pump_b1\")\n  |> last()"
    }
   ]
  },
  {
   "title": "PUMP D2",
   "type": "stat",
   "gridPos": { "x": 12, "y": 6, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"pump_b2\")\n  |> last()"
    }
   ]
  },
  { "title": "🌀 FAN", "type": "row", "gridPos": { "x": 0, "y": 10, "w": 24, "h": 1 } },
  {
   "title": "FAN A1",
   "type": "stat",
   "gridPos": { "x": 0, "y": 11, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"fan_a1\")\n  |> last()"
    }
   ]
  },
  {
   "title": "FAN B1",
   "type": "stat",
   "gridPos": { "x": 4, "y": 11, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"fan_b1\")\n  |> last()"
    }
   ]
  },
  {
   "title": "FAN B2",
   "type": "stat",
   "gridPos": { "x": 8, "y": 11, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CronusFarm\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"tele\" and r._field == \"fan_b2\")\n  |> last()"
    }
   ]
  }
 ]
}